colors =[]
print('Введите 10 цветов:')
colors.append(input('1'))
colors.append(input('2'))
colors.append(input('3'))
colors.append(input('4'))
colors.append(input('5'))
colors.append(input('6'))
colors.append(input('7'))
colors.append(input('8'))
colors.append(input('9'))
colors.append(input('10'))
colors.sort()
print(colors)
x = int(input('введите число от 0 до 4'))
y = int(input('введите число от 5 до 9'))
print(colors[x:y])